// source: analysis.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('analysis_dev_outreach_test_contractai_test.AnalysisResult', null, global);
goog.exportSymbol('analysis_dev_outreach_test_contractai_test.AnalyzeRequest', null, global);
goog.exportSymbol('analysis_dev_outreach_test_contractai_test.AnalyzeResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
analysis_dev_outreach_test_contractai_test.AnalyzeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(analysis_dev_outreach_test_contractai_test.AnalyzeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  analysis_dev_outreach_test_contractai_test.AnalyzeRequest.displayName = 'analysis_dev_outreach_test_contractai_test.AnalyzeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
analysis_dev_outreach_test_contractai_test.AnalysisResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(analysis_dev_outreach_test_contractai_test.AnalysisResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  analysis_dev_outreach_test_contractai_test.AnalysisResult.displayName = 'analysis_dev_outreach_test_contractai_test.AnalysisResult';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
analysis_dev_outreach_test_contractai_test.AnalyzeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(analysis_dev_outreach_test_contractai_test.AnalyzeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  analysis_dev_outreach_test_contractai_test.AnalyzeResponse.displayName = 'analysis_dev_outreach_test_contractai_test.AnalyzeResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
analysis_dev_outreach_test_contractai_test.AnalyzeRequest.prototype.toObject = function(opt_includeInstance) {
  return analysis_dev_outreach_test_contractai_test.AnalyzeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!analysis_dev_outreach_test_contractai_test.AnalyzeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
analysis_dev_outreach_test_contractai_test.AnalyzeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
userInput: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!analysis_dev_outreach_test_contractai_test.AnalyzeRequest}
 */
analysis_dev_outreach_test_contractai_test.AnalyzeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new analysis_dev_outreach_test_contractai_test.AnalyzeRequest;
  return analysis_dev_outreach_test_contractai_test.AnalyzeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!analysis_dev_outreach_test_contractai_test.AnalyzeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!analysis_dev_outreach_test_contractai_test.AnalyzeRequest}
 */
analysis_dev_outreach_test_contractai_test.AnalyzeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserInput(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
analysis_dev_outreach_test_contractai_test.AnalyzeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  analysis_dev_outreach_test_contractai_test.AnalyzeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!analysis_dev_outreach_test_contractai_test.AnalyzeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
analysis_dev_outreach_test_contractai_test.AnalyzeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserInput();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string user_input = 1;
 * @return {string}
 */
analysis_dev_outreach_test_contractai_test.AnalyzeRequest.prototype.getUserInput = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!analysis_dev_outreach_test_contractai_test.AnalyzeRequest} returns this
 */
analysis_dev_outreach_test_contractai_test.AnalyzeRequest.prototype.setUserInput = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
analysis_dev_outreach_test_contractai_test.AnalysisResult.prototype.toObject = function(opt_includeInstance) {
  return analysis_dev_outreach_test_contractai_test.AnalysisResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!analysis_dev_outreach_test_contractai_test.AnalysisResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
analysis_dev_outreach_test_contractai_test.AnalysisResult.toObject = function(includeInstance, msg) {
  var f, obj = {
dataMap: (f = msg.getDataMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!analysis_dev_outreach_test_contractai_test.AnalysisResult}
 */
analysis_dev_outreach_test_contractai_test.AnalysisResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new analysis_dev_outreach_test_contractai_test.AnalysisResult;
  return analysis_dev_outreach_test_contractai_test.AnalysisResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!analysis_dev_outreach_test_contractai_test.AnalysisResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!analysis_dev_outreach_test_contractai_test.AnalysisResult}
 */
analysis_dev_outreach_test_contractai_test.AnalysisResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getDataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
analysis_dev_outreach_test_contractai_test.AnalysisResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  analysis_dev_outreach_test_contractai_test.AnalysisResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!analysis_dev_outreach_test_contractai_test.AnalysisResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
analysis_dev_outreach_test_contractai_test.AnalysisResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * map<string, string> data = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
analysis_dev_outreach_test_contractai_test.AnalysisResult.prototype.getDataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!analysis_dev_outreach_test_contractai_test.AnalysisResult} returns this
 */
analysis_dev_outreach_test_contractai_test.AnalysisResult.prototype.clearDataMap = function() {
  this.getDataMap().clear();
  return this;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
analysis_dev_outreach_test_contractai_test.AnalyzeResponse.prototype.toObject = function(opt_includeInstance) {
  return analysis_dev_outreach_test_contractai_test.AnalyzeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!analysis_dev_outreach_test_contractai_test.AnalyzeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
analysis_dev_outreach_test_contractai_test.AnalyzeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
result: (f = msg.getResult()) && analysis_dev_outreach_test_contractai_test.AnalysisResult.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!analysis_dev_outreach_test_contractai_test.AnalyzeResponse}
 */
analysis_dev_outreach_test_contractai_test.AnalyzeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new analysis_dev_outreach_test_contractai_test.AnalyzeResponse;
  return analysis_dev_outreach_test_contractai_test.AnalyzeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!analysis_dev_outreach_test_contractai_test.AnalyzeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!analysis_dev_outreach_test_contractai_test.AnalyzeResponse}
 */
analysis_dev_outreach_test_contractai_test.AnalyzeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new analysis_dev_outreach_test_contractai_test.AnalysisResult;
      reader.readMessage(value,analysis_dev_outreach_test_contractai_test.AnalysisResult.deserializeBinaryFromReader);
      msg.setResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
analysis_dev_outreach_test_contractai_test.AnalyzeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  analysis_dev_outreach_test_contractai_test.AnalyzeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!analysis_dev_outreach_test_contractai_test.AnalyzeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
analysis_dev_outreach_test_contractai_test.AnalyzeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResult();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      analysis_dev_outreach_test_contractai_test.AnalysisResult.serializeBinaryToWriter
    );
  }
};


/**
 * optional AnalysisResult result = 1;
 * @return {?analysis_dev_outreach_test_contractai_test.AnalysisResult}
 */
analysis_dev_outreach_test_contractai_test.AnalyzeResponse.prototype.getResult = function() {
  return /** @type{?analysis_dev_outreach_test_contractai_test.AnalysisResult} */ (
    jspb.Message.getWrapperField(this, analysis_dev_outreach_test_contractai_test.AnalysisResult, 1));
};


/**
 * @param {?analysis_dev_outreach_test_contractai_test.AnalysisResult|undefined} value
 * @return {!analysis_dev_outreach_test_contractai_test.AnalyzeResponse} returns this
*/
analysis_dev_outreach_test_contractai_test.AnalyzeResponse.prototype.setResult = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!analysis_dev_outreach_test_contractai_test.AnalyzeResponse} returns this
 */
analysis_dev_outreach_test_contractai_test.AnalyzeResponse.prototype.clearResult = function() {
  return this.setResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
analysis_dev_outreach_test_contractai_test.AnalyzeResponse.prototype.hasResult = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, analysis_dev_outreach_test_contractai_test);
